"""empty message

Revision ID: 400f7bb64739
Revises: 453de1ed833c
Create Date: 2020-06-09 22:54:25.970105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400f7bb64739'
down_revision = '453de1ed833c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ekgdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ekgdata')
    # ### end Alembic commands ###
