"""empty message

Revision ID: 67288b16b24c
Revises: 84645ea84943
Create Date: 2020-06-09 23:01:30.935584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67288b16b24c'
down_revision = '84645ea84943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ekgdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ekgdata')
    # ### end Alembic commands ###
